name: easysms
description: >-
  Easy to use, simple configuration can send SMS messages to Phone. 
  Easily expandable gateways, messages customized according to scenarios.
version: 3.0.1
repository: https://github.com/odroe/easysms

environment:
  sdk: ^3.0.0

dependencies:
  crypto: ^3.0.2
  webfetch: ^0.0.17

dev_dependencies:
  lints: ">=2.0.1 <5.0.0"
  test: ^1.23.1
