name: easysms
description: >-
  Easy to use, simple configuration can send SMS messages to Phone. 
  Easily expandable gateways, messages customized according to scenarios.
version: 2.1.0
repository: https://github.com/odroe/easysms

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  crypto: ^3.0.2
  http: ^0.13.5

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.1
