name: easysms
description: >-
  Easy to use, simple configuration can send SMS messages to Phone. 
  Easily expandable gateways, messages customized according to scenarios.
version: 2.1.1
repository: https://github.com/odroe/easysms

environment:
  sdk: ^3.0.0

dependencies:
  crypto: ^3.0.2
  webfetch: ^0.0.14

dev_dependencies:
  lints: ^2.0.1
  test: ^1.23.1
