name: release-please
on:
  push:
    branches:
      - main
    paths:
      - 'lib/**'
      - 'pubspec.yaml'
      - '.github/workflows/release-please.yml'
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          release-type: dart
